### ISSUE TITLE
Nibe heating/cooling

### ISSUE THREAD

**Issue by owenselles** [hp-net/homebridge-nibe#172] opened 2023-02-22 10:16 UTC
The Nibe heating/cooling(nibe-thermostat-0) function shows the current temp of water flow but not the set room temperature. is it possible to add a switch to see the current room temp and the set temp instead of the flow.

**Comment by hpruszyn** [comment] 2023-02-22 10:27
@owenselles this is a duplicate of https://github.com/hp-net/homebridge-nibe/issues/162.

**Closed as completed by hpruszyn** 2023-02-22 10:27 UTC
Labels: duplicate, enhancement
